name: Check Missing Translation Keys

on:
  push:
    branches: [ main ]
    paths:
      - "pylon-core/src/main/resources/lang/en.yml"
      - "pylon-core/src/main/resources/lang/enws.yml"
  workflow_dispatch:

jobs:
  check-missing-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract all keys from en.yml
        run: |
          yq eval '.. | select(. == "*") | (path | join("."))' pylon-core/src/main/resources/lang/en.yml | sort > en_keys.txt

      - name: Extract all keys from enws.yml
        run: |
          yq eval '.. | select(. == "*") | (path | join("."))' pylon-core/src/main/resources/lang/enws.yml | sort > enws_keys.txt

      - name: Compare keys
        id: compare
        run: |
          missing=$(comm -23 en_keys.txt enws_keys.txt || true)
          extra=$(comm -13 en_keys.txt enws_keys.txt || true)
          
          if [ -n "$missing" ] || [ -n "$extra" ]; then          
            if [ -n "$missing" ]; then
              echo "## Missing keys (in \`en.yml\` but not in \`enws.yml\`)" >> key_diff.md
              echo "" >> key_diff.md
              echo "$missing" | while read line; do
                echo "- [ ] \`$line\`" >> key_diff.md
              done
              echo "" >> key_diff.md
            fi
          
            if [ -n "$extra" ]; then
              echo "## Outdated keys (in \`enws.yml\` but not in \`en.yml\`)" >> key_diff.md
              echo "" >> key_diff.md
              echo "$extra" | while read line; do
                echo "- [ ] \`$line\`" >> key_diff.md
              done
              echo "" >> key_diff.md
            fi
          
            echo "has_differences=true" >> $GITHUB_OUTPUT
          else
            echo "has_differences=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue if differences exist
        if: steps.compare.outputs.has_differences == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Inconsistent `en.yml` and `enws.yml`"
          content-filepath: key_diff.md
          assignees: Seggan
