name: Kotlin CI with Gradle

on:
  push:
    branches:
      - master
    paths:
      - 'plugin/**'
      - 'test/**'
      - 'build.gradle.kts'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'plugin/**'
      - 'test/**'
      - 'build.gradle.kts'
  workflow_call:
    inputs:
      version:
        default: ${{ github.run_number }}
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.2

      - name: Build with Gradle Wrapper
        run: ./gradlew :plugin:shadowJar -Pversion=${{ inputs.version || github.run_number }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: pylon-core-${{ inputs.version || github.run_number }}
          path: 'plugin/build/libs/pylon-core-${{ inputs.version || github.run_number }}.jar'

  dependency-submission:
    needs: [ build ]

    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.2.2

  test-build:
    needs: [ build ]
    uses: ./.github/workflows/live-testing.yml
